db:
  type: postgres
  host: dpg-d70i5jp4tr6s73e6rke0-a
  port: 5432
  name: carcamwiki_db_ompu
  user: carcamwiki_db_ompu_user
  password: lhQ9r5GbIBKERV2mB6RRnYPjSWQW4TMU

port: 10000
host: 0.0.0.0
